"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](yellow)\
$username[](bg:pink fg:yellow)\
$directory[](bg:lavender fg:pink)\
$git_branch[](bg:mauve fg:lavender)\
$rust[](bg:peach fg:mauve)\
$time\
[](peach)\
$line_break\
$character
"""

palette = "catppuccin_macchiato"
add_newline = false

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[username]
format = '[󰄛 $user ]($style)'
style_user = 'bg:yellow fg:bold base'
style_root = 'bg:peach'
show_always = true

[directory]
format = "[ $path ]($style)"
style = 'bg:pink fg:bold base'
truncation_symbol = '…/'

[directory.substitutions]
"Downloads" = "󰉍 "
"Pictures" = "󰉏 "
".config" = " "

[git_branch]
format = "[ $symbol $branch(:$remote_branch) ]($style)"
symbol = ""
style = "bg:lavender fg:bold base"

[time]
disabled = false
format = "[ 󰅐 $time]($style)"
time_format = "%H:%M"
style = "bg:peach fg:bold base"

[cmd_duration]
format = "[]($style) $duration"
style = "yellow"

[rust]
symbol = ""
format = '[ $symbol $version-$toolchain ]($style)'
style = 'bg:mauve fg:bold base'

[package]
disabled = true

